# Generated by Django 4.2 on 2024-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.IntegerField(unique=True, verbose_name='Internal ID')),
                ('customer_id', models.CharField(max_length=255, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('sales_rep', models.CharField(max_length=255, verbose_name='Sales Rep.')),
                ('billing_address_1', models.TextField(blank=True, null=True, verbose_name='Billing Address 1')),
                ('billing_address_2', models.TextField(blank=True, null=True, verbose_name='Billing Address 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State (Billing state/province)')),
                ('zip', models.IntegerField(verbose_name='Zip')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Rental Customer',
            },
        ),
    ]
