# Generated by Django 4.2 on 2024-10-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcustomer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='rentalcustomer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='rentalcustomer',
            name='sales_rep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales Rep.'),
        ),
        migrations.AlterField(
            model_name='rentalcustomer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State (Billing state/province)'),
        ),
        migrations.AlterField(
            model_name='rentalcustomer',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip'),
        ),
    ]
