# Generated by Django 4.2 on 2024-10-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_customer', '0002_alter_rentalcustomer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcustomer',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='rentalcustomer',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
