# Generated by Django 4.2 on 2024-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_customer', '0003_rentalcustomer_lat_rentalcustomer_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcustomer',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip'),
        ),
    ]
