# Generated by Django 4.2 on 2025-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_customer', '0004_alter_rentalcustomer_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcustomer',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Rental Cutomer Email'),
            preserve_default=False,
        ),
    ]
