# Generated by Django 4.2 on 2025-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.IntegerField(unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('material_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_item_number', models.CharField(max_length=255)),
                ('material_factor', models.FloatField(blank=True, null=True)),
                ('additional_material_factor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proposal Additional Material',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.IntegerField(unique=True)),
                ('family', models.CharField(max_length=255)),
                ('parent', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('primary_units_type', models.CharField(max_length=50)),
                ('primary_stock_unit', models.CharField(max_length=50)),
                ('std_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_vendor', models.CharField(max_length=255)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proposal Product',
            },
        ),
    ]
