# Generated by Django 4.2 on 2024-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
