# Generated by Django 4.2 on 2024-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Proposal Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
