# Generated by Django 4.2 on 2024-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_product_internal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.IntegerField(unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('material_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_item_number', models.CharField(max_length=255)),
                ('material_factor', models.FloatField(blank=True, null=True)),
                ('additional_material_factor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proposal Additional Material',
            },
        ),
    ]
