# Generated by Django 4.2 on 2024-10-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_additionalmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
