# Generated by Django 4.2 on 2024-08-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Internal Id')),
                ('sales_rep', models.CharField(max_length=255, verbose_name='Sales Rep')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('opportunity_class', models.CharField(max_length=255, verbose_name='Opportunity Class')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('document_number', models.CharField(max_length=255, verbose_name='Document Number')),
                ('ranch_address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Ranch Address')),
                ('opportunity_status', models.CharField(max_length=255, verbose_name='Opportunity Status')),
                ('projected_total', models.CharField(verbose_name='Projected Total')),
                ('expected_margin', models.FloatField(verbose_name='Expected Margin')),
                ('margin_amount', models.CharField(verbose_name='Margin Amount')),
                ('win_probability', models.CharField(blank=True, null=True, verbose_name='Win Probability')),
                ('expected_close', models.DateField(verbose_name='Expected Close')),
                ('opportunity_notes', models.TextField(blank=True, null=True, verbose_name='Opportunity Notes')),
                ('scope', models.TextField(blank=True, null=True, verbose_name='Scope')),
                ('designer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Designer')),
                ('estimator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimator')),
                ('pump_electrical_designer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pump & Electrical Designer')),
                ('design_estimation_note', models.TextField(blank=True, null=True, verbose_name='Design/Estimation Note')),
                ('estimation_stage', models.CharField(choices=[('Select Task Code', 'Select Task Code'), ('Upload CAD File', 'Upload CAD File'), ('Material List', 'Material List'), ('Task Mapping', 'Task Mapping'), ('Generate Estimate', 'Generate Estimate'), ('Proposal Creation', 'Proposal Creation'), ('Proposal Preview', 'Proposal Preview'), ('Final Document', 'Final Document')], default='Select Task Code', max_length=50, verbose_name='Estimation Stage')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Proposal Opportunitie',
            },
        ),
        migrations.CreateModel(
            name='SelectTaskCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity', to='opportunity.opportunity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.task')),
            ],
            options={
                'verbose_name': 'Proposal TaskCode',
            },
        ),
        migrations.CreateModel(
            name='PreliminaryMaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('irricad_imported_quantities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Irricad Imported Quantities')),
                ('glue_and_additional_mat_quantities', models.CharField(blank=True, max_length=255, null=True, verbose_name="Glue & Additional Mat'l Quantities")),
                ('combined_quantities_from_both_import', models.CharField(blank=True, max_length=255, null=True, verbose_name='Combined Quantities from both Import')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('item_number', models.CharField(max_length=255, verbose_name='Item Number')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('bag_bundle_quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bag/Bundle Quantity')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_preliminary_list', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Proposal Preliminary Material',
            },
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('item_number', models.CharField(max_length=255, verbose_name='Item Number')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_materials', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Proposal Material List',
            },
        ),
        migrations.CreateModel(
            name='GlueAndAdditionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('item_number', models.CharField(max_length=255, verbose_name='Item Number')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_glue_and_additional_material', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Proposal Glue & Additional Material',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='documents/', verbose_name='Document')),
                ('stage', models.CharField(choices=[('Select Task Code', 'Select Task Code'), ('Upload CAD File', 'Upload CAD File'), ('Material List', 'Material List'), ('Task Mapping', 'Task Mapping'), ('Generate Estimate', 'Generate Estimate'), ('Proposal Creation', 'Proposal Creation'), ('Proposal Preview', 'Proposal Preview'), ('Final Document', 'Final Document')], default='Select Task Code', max_length=50, verbose_name='Stage')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Proposal Document',
            },
        ),
    ]
