# Generated by Django 4.2 on 2024-08-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "internal_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Internal Id",
                    ),
                ),
                (
                    "sales_rep",
                    models.CharField(max_length=255, verbose_name="Sales Rep"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                (
                    "opportunity_class",
                    models.CharField(max_length=255, verbose_name="Opportunity Class"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "document_number",
                    models.CharField(max_length=255, verbose_name="Document Number"),
                ),
                (
                    "ranch_address",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ranch Address",
                    ),
                ),
                (
                    "opportunity_status",
                    models.CharField(max_length=255, verbose_name="Opportunity Status"),
                ),
                ("projected_total", models.FloatField(verbose_name="Projected Total")),
                (
                    "expected_margin",
                    models.IntegerField(verbose_name="Expected Margin"),
                ),
                ("margin_amount", models.FloatField(verbose_name="Margin Amount")),
                (
                    "win_probability",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Win Probability"
                    ),
                ),
                ("expected_close", models.DateTimeField(verbose_name="Expected Close")),
                (
                    "opportunity_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Opportunity Notes"
                    ),
                ),
                ("scope", models.TextField(verbose_name="Scope")),
                (
                    "designer",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Designer"
                    ),
                ),
                (
                    "estimator",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Estimator"
                    ),
                ),
                (
                    "pump_electrical_designer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pump & Electrical Designer",
                    ),
                ),
                (
                    "design_estimation_note",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Design/Estimation Note",
                    ),
                ),
                (
                    "estimation_stage",
                    models.CharField(
                        choices=[
                            ("Select Task Code", "Select Task Code"),
                            ("Upload CAD File", "Upload CAD File"),
                            ("Material List", "Material List"),
                            ("Task Mapping", "Task Mapping"),
                            ("Generate Estimate", "Generate Estimate"),
                            ("Proposal Creation", "Proposal Creation"),
                            ("Proposal Preview", "Proposal Preview"),
                            ("Final Document", "Final Document"),
                        ],
                        default="Select Task Code",
                        max_length=50,
                        verbose_name="Estimation Stage",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
