# Generated by Django 4.2 on 2024-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="customer",
            field=models.CharField(max_length=255, verbose_name="Customer"),
        ),
    ]
