# Generated by Django 4.2 on 2024-09-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_options_alter_opportunity_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='include',
            field=models.BooleanField(default=True, verbose_name='Include Items'),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='labor_gp_percent',
            field=models.FloatField(blank=True, default=25.0, max_length=255, null=True, verbose_name='Labor GP %'),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='mat_gp_percent',
            field=models.FloatField(blank=True, default=10.0, max_length=255, null=True, verbose_name='Mat GP %'),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='s_and_h',
            field=models.FloatField(blank=True, default=10.0, max_length=255, null=True, verbose_name='S & H'),
        ),
        migrations.CreateModel(
            name='ProposalCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_creation_opportunity', to='opportunity.opportunity')),
                ('task_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_tasks', to='opportunity.taskmapping')),
            ],
            options={
                'verbose_name': 'Proposal Creation',
            },
        ),
    ]
