# Generated by Django 4.2 on 2024-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0002_alter_opportunity_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="win_probability",
            field=models.CharField(
                blank=True, null=True, verbose_name="Win Probability"
            ),
        ),
    ]
