# Generated by Django 4.2 on 2024-09-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_taskmapping_include_taskmapping_labor_gp_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Name'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='ranch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ranch Name'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Number')),
                ('invoice_data', models.DateTimeField(blank=True, null=True, verbose_name='Invoice Data')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('deposit_amount', models.FloatField(default=0.0, verbose_name='Deposit Amount')),
                ('deu_amount', models.FloatField(default=0.0, verbose_name='Deu Amount')),
                ('tax_rate', models.FloatField(default=0.0, verbose_name='Tax Rate')),
                ('sales_tax', models.FloatField(default=0.0, verbose_name='Sales Tax')),
                ('other_tax', models.FloatField(default=0.0, verbose_name='Other Tax')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Remit To')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_opportunity', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Proposal Invoice',
            },
        ),
    ]
