# Generated by Django 4.2 on 2024-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0003_alter_opportunity_win_probability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="expected_close",
            field=models.CharField(max_length=255, verbose_name="Expected Close"),
        ),
    ]
