# Generated by Django 4.2 on 2024-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_opportunity_job_opportunity_job_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Proposal Opportunities'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='document_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Document Number'),
        ),
    ]
