# Generated by Django 4.2 on 2024-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0004_alter_opportunity_expected_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="expected_close",
            field=models.DateField(verbose_name="Expected Close"),
        ),
    ]
