# Generated by Django 4.2 on 2024-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_alter_opportunity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Buyer Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Position'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_address',
            field=models.TextField(blank=True, null=True, verbose_name='Deposit Address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seller Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller Position'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='document_number',
            field=models.CharField(max_length=255, verbose_name='Document Number'),
        ),
    ]
