# Generated by Django 4.2 on 2024-08-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("opportunity", "0005_alter_opportunity_expected_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="customer.customer",
            ),
        ),
    ]
