# Generated by Django 4.2 on 2024-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_invoice_buyer_invoice_buyer_date_invoice_buyer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='term_and_condition',
            field=models.JSONField(blank=True, null=True, verbose_name='Term & Condition'),
        ),
    ]
