# Generated by Django 4.2 on 2024-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0006_alter_opportunity_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="customer",
            field=models.CharField(default=1, max_length=255, verbose_name="Customer"),
            preserve_default=False,
        ),
    ]
