# Generated by Django 4.2 on 2024-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_opportunity_term_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='extra_description',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra Description'),
        ),
    ]
