# Generated by Django 4.2 on 2024-08-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
        ("customer", "0001_initial"),
        ("opportunity", "0008_alter_opportunity_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="design_estimation_note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Design/Estimation Note"
            ),
        ),
        migrations.CreateModel(
            name="SelectTaskCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity",
                        to="opportunity.opportunity",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="task.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
