# Generated by Django 4.2 on 2024-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_taskmapping_extra_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='approve',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Approve & Initial'),
        ),
    ]
