# Generated by Django 4.2 on 2024-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_taskmapping_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedproduct',
            name='is_select',
            field=models.BooleanField(default=False, verbose_name='Is Selected'),
        ),
    ]
