# Generated by Django 4.2 on 2024-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0009_alter_opportunity_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.FileField(upload_to="documents/", verbose_name="Document"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Select Task Code", "Select Task Code"),
                            ("Upload CAD File", "Upload CAD File"),
                            ("Material List", "Material List"),
                            ("Task Mapping", "Task Mapping"),
                            ("Generate Estimate", "Generate Estimate"),
                            ("Proposal Creation", "Proposal Creation"),
                            ("Proposal Preview", "Proposal Preview"),
                            ("Final Document", "Final Document"),
                        ],
                        default="Select Task Code",
                        max_length=50,
                        verbose_name="Stage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
