# Generated by Django 4.2 on 2024-10-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_assignedproduct_is_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='assign_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assign to'),
        ),
    ]
