# Generated by Django 4.2 on 2024-08-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0010_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
    ]
