# Generated by Django 4.2 on 2024-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0011_taskmapping_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='is_assign_task',
            field=models.BooleanField(default=False, verbose_name='Is Assign Task'),
        ),
    ]
