# Generated by Django 4.2 on 2024-11-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0012_taskmapping_is_assign_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glueandadditionalmaterial',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
    ]
