# Generated by Django 4.2 on 2024-08-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0012_document_opportunity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="expected_margin",
            field=models.FloatField(verbose_name="Expected Margin"),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="margin_amount",
            field=models.CharField(verbose_name="Margin Amount"),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="projected_total",
            field=models.CharField(verbose_name="Projected Total"),
        ),
    ]
