# Generated by Django 4.2 on 2024-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0013_alter_glueandadditionalmaterial_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedproduct',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
