# Generated by Django 4.2 on 2024-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0013_alter_opportunity_expected_margin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="scope",
            field=models.TextField(blank=True, null=True, verbose_name="Scope"),
        ),
    ]
