# Generated by Django 4.2 on 2024-08-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0014_alter_opportunity_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('item_number', models.CharField(max_length=255, verbose_name='Item Number')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_materials', to='opportunity.opportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
