# Generated by Django 4.2 on 2024-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0014_assignedproduct_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecttaskcode',
            name='task_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Task Description'),
        ),
    ]
