# Generated by Django 4.2 on 2025-02-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0015_selecttaskcode_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='tax_rate',
            field=models.CharField(blank=True, default='25.00%', null=True, verbose_name='Tax Rate'),
        ),
    ]
