# Generated by Django 4.2 on 2024-08-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0015_materiallist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryMaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('irricad_imported_quantities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Irricad Imported Quantities')),
                ('glue_and_additional_mat_Quantities', models.CharField(blank=True, max_length=255, null=True, verbose_name="Glue & Additional Mat'l Quantities")),
                ('combined_quantities_from_both_import', models.CharField(blank=True, max_length=255, null=True, verbose_name='Combined Quantities from both Import')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('item_number', models.CharField(max_length=255, verbose_name='Item Number')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('bag_bundle_quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bag/Bundle Quantity')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_preliminary_list', to='opportunity.opportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlueAndAdditionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('item_number', models.CharField(max_length=255, verbose_name='Item Number')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_glue_and_additional_material', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Glue & Additional Material',
                'verbose_name_plural': 'Glue & Additional Material',
            },
        ),
    ]
