# Generated by Django 4.2 on 2025-03-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_opportunity_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='linked_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_mapping_linked_tasks', to='opportunity.taskmapping'),
        ),
    ]
