# Generated by Django 4.2 on 2024-08-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_preliminarymateriallist_glueandadditionalmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preliminarymateriallist',
            old_name='glue_and_additional_mat_Quantities',
            new_name='glue_and_additional_mat_quantities',
        ),
    ]
