# Generated by Django 4.2 on 2024-08-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0017_rename_glue_and_additional_mat_quantities_preliminarymateriallist_glue_and_additional_mat_quantities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Proposal Document'},
        ),
        migrations.AlterModelOptions(
            name='glueandadditionalmaterial',
            options={'verbose_name': 'Proposal Glue & Additional Material'},
        ),
        migrations.AlterModelOptions(
            name='materiallist',
            options={'verbose_name': 'Proposal Material List'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Proposal Opportunitie'},
        ),
        migrations.AlterModelOptions(
            name='preliminarymateriallist',
            options={'verbose_name': 'Proposal Preliminary Material'},
        ),
        migrations.AlterModelOptions(
            name='selecttaskcode',
            options={'verbose_name': 'Proposal TaskCode'},
        ),
    ]
