# Generated by Django 4.2 on 2024-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('address', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Rental Warehouse',
            },
        ),
    ]
