# Generated by Django 4.2 on 2024-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalwarehouse',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='rentalwarehouse',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
