# Generated by Django 4.2 on 2024-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Account Manager Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Account Manager Email')),
            ],
            options={
                'verbose_name': 'Rental Account Manager',
            },
        ),
    ]
