# Generated by Django 4.2 on 2025-02-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='manager_id',
            field=models.CharField(max_length=255, null=True, blank=True, verbose_name='Manager ID')
        ),
    ]
