# Generated by Django 4.2 on 2025-02-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_accountmanager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='manager_id',
            field=models.CharField(unique=True, verbose_name='Manager ID'),
        ),
    ]
