# Generated by Django 4.2 on 2025-01-17 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_customer', '0004_alter_rentalcustomer_zip'),
        ('rental_product', '0003_remove_rentalproduct_last_updated_by'),
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('delivery_qty', models.IntegerField()),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('check_in_date', models.DateField()),
                ('removal_date', models.DateField()),
                ('inspection_date', models.DateField()),
                ('pickup_site', models.CharField(max_length=255)),
                ('delivery_site', models.CharField(max_length=255)),
                ('po_number', models.CharField(max_length=50)),
                ('shipping_carrier', models.CharField(choices=[('Internal', 'Internal'), ('Hired', 'Hired')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('Pick Up', 'Pick Up'), ('Check Out', 'Check Out'), ('Delivered', 'Delivered'), ('Check In', 'Check In'), ('Create Return Delivery', 'Create Return Delivery'), ('Create Delivery', 'Create Delivery')], default='Pick Up', max_length=50, verbose_name='Delivery Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('link_netsuite', models.URLField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_location', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('water_source', models.CharField(blank=True, max_length=255, null=True)),
                ('crop', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('recurring_order', models.BooleanField(default=False)),
                ('repeat_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=255)),
                ('repeat_value', models.PositiveIntegerField(blank=True, null=True)),
                ('repeat_start_date', models.DateField(blank=True, null=True)),
                ('repeat_end_date', models.DateField(blank=True, null=True)),
                ('recurring_type', models.CharField(choices=[('Internal', 'Internal'), ('Hide', 'Hide')], default='Daily', max_length=255)),
                ('order_status', models.CharField(choices=[('Pick Up', 'Pick Up'), ('Check Out', 'Check Out'), ('Delivered', 'Delivered'), ('Check In', 'Check In'), ('Create Return Delivery', 'Create Return Delivery'), ('Create Delivery', 'Create Delivery')], default='Pick Up', max_length=50, verbose_name='Order Status')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_order', to='account_manager.accountmanager')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_order', to='rental_customer.rentalcustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_return_orders', to='rent_process.delivery')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='rent_process.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_order', models.CharField(max_length=50)),
                ('return_qty', models.IntegerField()),
                ('return_po_number', models.CharField(max_length=50)),
                ('returned_pickup_date', models.DateField()),
                ('returned_delivery_date', models.DateField()),
                ('returned_pickup_site', models.CharField(max_length=255)),
                ('returned_delivery_site', models.CharField(max_length=255)),
                ('shipping_carrier', models.CharField(choices=[('Internal', 'Internal'), ('Hired', 'Hired')], max_length=20)),
                ('deliver_to_customer', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_delivery', to='rent_process.delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurring_order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to='rent_process.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('per_unit_price', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rent_process.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='rental_product.rentalproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='rent_process.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_products', to='rental_product.rentalproduct'),
        ),
    ]
