# Generated by Django 4.2 on 2025-01-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='repeat_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=255),
        ),
    ]
