# Generated by Django 4.2 on 2025-02-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0002_alter_order_repeat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='removal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
