# Generated by Django 4.2 on 2025-02-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0002_alter_order_repeat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormPermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.BooleanField(default=False)),
                ('account_manager', models.BooleanField(default=False)),
                ('link_netsuite', models.BooleanField(default=False)),
                ('region', models.BooleanField(default=False)),
                ('pick_up_location', models.BooleanField(default=False)),
                ('delivery_location', models.BooleanField(default=False)),
                ('water_source', models.BooleanField(default=False)),
                ('crop', models.BooleanField(default=False)),
                ('rent_amount', models.BooleanField(default=False)),
                ('rental_start_date', models.BooleanField(default=False)),
                ('rental_end_date', models.BooleanField(default=False)),
                ('recurring_order', models.BooleanField(default=False)),
                ('repeat_type', models.BooleanField(default=False)),
                ('repeat_value', models.BooleanField(default=False)),
                ('repeat_start_date', models.BooleanField(default=False)),
                ('repeat_end_date', models.BooleanField(default=False)),
                ('rental_period', models.BooleanField(default=False)),
                ('customer_email', models.BooleanField(default=False)),
                ('rent_per_month', models.BooleanField(default=False)),
                ('equipment_id', models.BooleanField(default=False)),
                ('equipment_name', models.BooleanField(default=False)),
                ('product', models.BooleanField(default=False)),
                ('quantity', models.BooleanField(default=False)),
                ('per_unit_price', models.BooleanField(default=False)),
            ],
        ),
    ]
