# Generated by Django 4.2 on 2025-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0003_alter_delivery_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
