# Generated by Django 4.2 on 2025-02-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0003_orderformpermissionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderformpermissionmodel',
            name='account_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderformpermissionmodel',
            name='customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderformpermissionmodel',
            name='customer_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderformpermissionmodel',
            name='repeat_type',
            field=models.BooleanField(default=True),
        ),
    ]
