# Generated by Django 4.2 on 2025-02-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0004_alter_delivery_po_number'),
        ('rent_process', '0004_alter_orderformpermissionmodel_account_manager_and_more'),
    ]

    operations = [
    ]
