# Generated by Django 4.2 on 2025-02-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0005_merge_20250213_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderformpermissionmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderformpermissionmodel',
            name='rental_end_date',
        ),
        migrations.RemoveField(
            model_name='orderformpermissionmodel',
            name='rental_start_date',
        ),
    ]
