# Generated by Django 4.2 on 2025-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0006_remove_orderformpermissionmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
