# Generated by Django 4.2 on 2025-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0006_remove_orderformpermissionmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='unique_delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
