# Generated by Django 4.2 on 2025-02-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0007_alter_delivery_check_in_date'),
        ('rent_process', '0007_delivery_unique_delivery_id'),
    ]

    operations = [
    ]
