# Generated by Django 4.2 on 2025-02-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0008_merge_20250219_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Create Delivery', 'Create Delivery'), ('Pick Up Ticket', 'Pick Up Ticket'), ('Check Out', 'Check Out'), ('Delivered To Customer', 'Delivered To Customer'), ('Create Return Delivery', 'Create Return Delivery'), ('Return Pick Up Ticket', 'Return Pick Up Ticket'), ('Check In', 'Check In'), ('Inspection Completed', 'Inspection Completed')], default='Create Delivery', max_length=50, verbose_name='Delivery Status'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='documents/', verbose_name='Document')),
                ('stage', models.CharField(choices=[('Create Delivery', 'Create Delivery'), ('Pick Up Ticket', 'Pick Up Ticket'), ('Check Out', 'Check Out'), ('Delivered To Customer', 'Delivered To Customer'), ('Create Return Delivery', 'Create Return Delivery'), ('Return Pick Up Ticket', 'Return Pick Up Ticket'), ('Check In', 'Check In'), ('Inspection Completed', 'Inspection Completed')], default='Create Delivery', max_length=50, verbose_name='Stage')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rent_process.order')),
            ],
            options={
                'verbose_name': 'Proposal Document',
            },
        ),
    ]
