# Generated by Django 4.2 on 2025-03-17 05:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0010_alter_document_options_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=django_countries.fields.CountryField(blank=True, max_length=255, null=True),
        ),
    ]
