# Generated by Django 4.2 on 2025-03-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0011_remove_returndelivery_return_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returndelivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='returndelivery',
            name='order',
        ),
        migrations.AddField(
            model_name='returnorder',
            name='return_order_unique_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='returndelivery',
            name='return_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_delivery_order', to='rent_process.returnorder'),
        ),
    ]
