# Generated by Django 4.2 on 2025-03-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0012_remove_returndelivery_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
