# Generated by Django 4.2 on 2025-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0014_remove_returndelivery_return_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndelivery',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returndelivery',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returndelivery',
            name='removal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
