# Generated by Django 4.2 on 2025-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0015_returndelivery_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndelivery',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
