# Generated by Django 4.2 on 2025-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0015_returndelivery_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='direct_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
