# Generated by Django 4.2 on 2025-03-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0016_delivery_direct_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndelivery',
            name='direct_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
