# Generated by Django 4.2 on 2025-03-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0016_returndelivery_inspection_date'),
        ('rent_process', '0017_returndelivery_direct_delivery'),
    ]

    operations = [
    ]
