# Generated by Django 4.2 on 2025-03-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0011_alter_order_region'),
        ('rent_process', '0019_alter_returndeliveryitem_return_status'),
    ]

    operations = [
    ]
