# Generated by Django 4.2 on 2025-03-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_process', '0020_merge_20250317_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link_netsuite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
