# Generated by Django 4.2 on 2025-01-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_product', '0003_remove_rentalproduct_last_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('inspection', 'Inspection'), ('purchase', 'Purchase'), ('wh_difference', 'Warehouse Difference'), ('other', 'Other')], default='other', max_length=50)),
                ('comment', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_product.rentalproduct')),
                ('rental_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='rental_product.rentalproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
