# Generated by Django 4.2 on 2025-01-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='product',
        ),
    ]
