# Generated by Django 4.2 on 2025-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_remove_stockadjustment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
