# Generated by Django 4.2 on 2025-01-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_alter_stockadjustment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
