# Generated by Django 4.2 on 2025-01-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0004_alter_stockadjustment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('other', 'Other'), ('inspection', 'Inspection'), ('purchase', 'Purchase'), ('wh_difference', 'Warehouse Difference')], default='other', max_length=50),
        ),
    ]
