# Generated by Django 4.2 on 2025-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('industry', models.CharField(help_text='e.g., Agriculture, Irrigation, Landscaping', max_length=100, verbose_name='Industry')),
                ('project_type', models.CharField(help_text='e.g., Drip Irrigation System, Sprinkler Installation', max_length=100, verbose_name='Project Type')),
                ('estimated_hours', models.IntegerField(help_text='Typical labor hours for this project type', verbose_name='Estimated Hours')),
                ('estimated_cost_min', models.DecimalField(decimal_places=2, help_text='Minimum typical project cost', max_digits=10, verbose_name='Estimated Cost (Min)')),
                ('estimated_cost_max', models.DecimalField(decimal_places=2, help_text='Maximum typical project cost', max_digits=10, verbose_name='Estimated Cost (Max)')),
                ('template_data', models.JSONField(help_text='Stores selected tasks, products, labor costs, and quantities', verbose_name='Template Data')),
                ('is_public', models.BooleanField(default=True, help_text='Public templates are available to all users', verbose_name='Public Template')),
                ('times_used', models.IntegerField(default=0, help_text='How many times this template has been used', verbose_name='Times Used')),
                ('thumbnail', models.ImageField(blank=True, help_text='Visual preview image for template browser', null=True, upload_to='template_thumbnails/', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Estimation Template',
                'verbose_name_plural': 'Estimation Templates',
                'ordering': ['-times_used', 'name'],
            },
        ),
    ]
