# Generated by Django 4.2 on 2025-10-01 16:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labour_cost', '0001_initial'),
        ('task', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_hours', models.DecimalField(decimal_places=2, help_text='Typical hours for this labour type', max_digits=10, verbose_name='Default Hours')),
                ('hours_formula', models.CharField(blank=True, help_text="e.g., 'acres * 1.5' for parameterized templates", max_length=255, verbose_name='Hours Formula')),
                ('is_local', models.BooleanField(default=True, help_text='Use local rate (True) or out-of-town rate (False)', verbose_name='Local Rate')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
            ],
            options={
                'verbose_name': 'Template Labour',
                'verbose_name_plural': 'Template Labour',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_quantity', models.DecimalField(decimal_places=2, help_text='Typical quantity needed', max_digits=10, verbose_name='Default Quantity')),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use template default', max_digits=5, null=True, verbose_name='Markup %')),
                ('quantity_formula', models.CharField(blank=True, help_text="e.g., 'acres * 50' for parameterized templates", max_length=255, verbose_name='Quantity Formula')),
                ('sequence', models.IntegerField(default=0, help_text='Order products appear within task', verbose_name='Sequence')),
            ],
            options={
                'verbose_name': 'Template Product',
                'verbose_name_plural': 'Template Products',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_hours', models.DecimalField(decimal_places=2, help_text='Typical hours for this task in this template', max_digits=10, verbose_name='Default Hours')),
                ('sequence', models.IntegerField(default=0, help_text='Order tasks appear in template', verbose_name='Sequence')),
                ('notes', models.TextField(blank=True, help_text='Template-specific notes or instructions', verbose_name='Notes')),
                ('hours_formula', models.CharField(blank=True, help_text="e.g., 'base_hours + (acres * 2)' for parameterized templates", max_length=255, verbose_name='Hours Formula')),
            ],
            options={
                'verbose_name': 'Template Task',
                'verbose_name_plural': 'Template Tasks',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='estimationtemplate',
            name='template_data',
        ),
        migrations.AddField(
            model_name='estimationtemplate',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='Default Margin %'),
        ),
        migrations.AddField(
            model_name='estimationtemplate',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Default Tax Rate %'),
        ),
        migrations.AddField(
            model_name='estimationtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null = public template available to all', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationtemplate',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='User-adjustable parameters like acres, rows, pump HP that compute quantities', verbose_name='Template Parameters'),
        ),
        migrations.AddField(
            model_name='estimationtemplate',
            name='schema_version',
            field=models.CharField(default='1.0', help_text='Template schema version for migration safety', max_length=10, verbose_name='Schema Version'),
        ),
        migrations.AlterField(
            model_name='estimationtemplate',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public templates are available to all organizations', verbose_name='Public Template'),
        ),
        migrations.AlterField(
            model_name='estimationtemplate',
            name='times_used',
            field=models.IntegerField(default=0, help_text='How many times this template has been used (will be per-org later)', verbose_name='Times Used'),
        ),
        migrations.AddIndex(
            model_name='estimationtemplate',
            index=models.Index(fields=['industry', 'project_type'], name='template_es_industr_0d606d_idx'),
        ),
        migrations.AddIndex(
            model_name='estimationtemplate',
            index=models.Index(fields=['is_public', 'organization'], name='template_es_is_publ_a2ce7e_idx'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='task',
            field=models.ForeignKey(help_text='Reference to actual task in catalog', on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='template.estimationtemplate'),
        ),
        migrations.AddField(
            model_name='templateproduct',
            name='product',
            field=models.ForeignKey(help_text='Reference to actual product in catalog', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='templateproduct',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_products', to='template.estimationtemplate'),
        ),
        migrations.AddField(
            model_name='templateproduct',
            name='template_task',
            field=models.ForeignKey(blank=True, help_text='Which task this product is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='template.templatetask'),
        ),
        migrations.AddField(
            model_name='templatelabour',
            name='labour_cost',
            field=models.ForeignKey(help_text='Reference to actual labour cost in catalog', on_delete=django.db.models.deletion.CASCADE, to='labour_cost.labourcost'),
        ),
        migrations.AddField(
            model_name='templatelabour',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_labour', to='template.estimationtemplate'),
        ),
        migrations.AddField(
            model_name='templatelabour',
            name='template_task',
            field=models.ForeignKey(blank=True, help_text='Which task this labour is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='template.templatetask'),
        ),
        migrations.AlterUniqueTogether(
            name='templatetask',
            unique_together={('template', 'task', 'sequence')},
        ),
    ]
