# Generated by Django 4.2 on 2024-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sales_rep', models.CharField(max_length=255)),
                ('billing_address_1', models.CharField(max_length=255)),
                ('billing_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proposal Customer',
            },
        ),
    ]
