# Generated by Django 4.2 on 2024-09-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Proposal Customer'},
        ),
    ]
