# Generated by Django 4.2 on 2024-08-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("internal_id", models.CharField(max_length=255, unique=True)),
                ("family", models.CharField(max_length=255)),
                ("parent", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("primary_units_type", models.CharField(max_length=50)),
                ("primary_stock_unit", models.CharField(max_length=50)),
                ("std_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preferred_vendor", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
