# Generated by Django 4.2 on 2024-08-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0011_document_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="opportunity.opportunity",
            ),
        ),
    ]
