# Generated by Django 4.2 on 2024-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labour_task', models.CharField(max_length=255, unique=True, verbose_name='Labour Task')),
                ('local_labour_rates', models.FloatField(blank=True, null=True, verbose_name='Local Labour Rates')),
                ('out_of_town_labour_rates', models.FloatField(blank=True, null=True, verbose_name='Out Of Labour Rates')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Proposal Labour Cost',
            },
        ),
    ]
