# Generated by Django 4.2 on 2024-08-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourcost',
            options={'verbose_name': 'Proposal Labour Cost'},
        ),
    ]
