# Generated by Django 4.2 on 2024-12-31 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_cost', '0002_alter_labourcost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourcost',
            options={'verbose_name': 'Proposal Labor Cost'},
        ),
    ]
