# Generated by Django 4.2 on 2025-01-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_product', '0002_alter_rentalproduct_last_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproduct',
            name='last_updated_by',
        ),
    ]
