# Generated by Django 4.2 on 2024-08-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_internal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Proposal Task'},
        ),
    ]
