# Generated by Django 4.2 on 2024-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_mobile_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mobile Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Username"
            ),
        ),
    ]
