# Generated by Django 4.2 on 2024-08-29 11:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_mobile_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Proposal', 'Proposal'), ('Rental', 'Rental')], max_length=20, null=True),
        ),
    ]
