# Generated by Django 4.2 on 2025-10-01 22:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunity', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materials_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Materials Total')),
                ('labor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Labor Total')),
                ('equipment_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Equipment Total')),
                ('subcontractor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subcontractor Total')),
                ('our_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of materials + labor + equipment + subs', max_digits=12, verbose_name='Our Cost')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Profit margin percentage', max_digits=5, verbose_name='Margin %')),
                ('margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Margin Amount')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Our cost + margin', max_digits=12, verbose_name='Sale Price')),
            ],
            options={
                'verbose_name': 'Bid Item Detail',
                'verbose_name_plural': 'Bid Item Details',
            },
        ),
        migrations.CreateModel(
            name='BidSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(help_text="e.g., '100', '200', 'A-1'", max_length=50, verbose_name='Item Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('engineer_estimate', models.DecimalField(blank=True, decimal_places=2, help_text="Agency's estimated cost from RFP", max_digits=12, null=True, verbose_name="Engineer's Estimate")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('estimating', 'Estimating'), ('quoted', 'Quoted'), ('complete', 'Complete'), ('not_needed', 'Not Needed')], default='draft', max_length=20, verbose_name='Status')),
                ('color_code', models.CharField(choices=[('green', '🟢 Green - Done'), ('red', '🔴 Red - Need Work'), ('yellow', '🟡 Yellow - Need Quote'), ('orange', '🟠 Orange - Waiting'), ('black', '⚫ Black - Not Needed')], default='red', max_length=20, verbose_name='Color Code')),
                ('sequence', models.IntegerField(default=0, help_text='Order in bid schedule', verbose_name='Sequence')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this bid item', verbose_name='Notes')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_schedule', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Bid Schedule Item',
                'verbose_name_plural': 'Bid Schedule Items',
                'ordering': ['sequence', 'item_code'],
                'unique_together': {('opportunity', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='BidItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('netsuite_internal_id', models.IntegerField(blank=True, help_text='Internal ID from Items42.xls for NetSuite import', null=True, verbose_name='NetSuite Internal ID')),
                ('name', models.CharField(help_text='Product name/description', max_length=255, verbose_name='Name')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(default='EA', help_text='e.g., EA, FT, GAL, LB', max_length=50, verbose_name='Unit')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (from NetSuite)', max_digits=10, verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Quantity × Unit Cost', max_digits=12, verbose_name='Total Cost')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='bid.biditem')),
                ('product', models.ForeignKey(blank=True, help_text='Product from catalog', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
            options={
                'verbose_name': 'Bid Item Material',
                'verbose_name_plural': 'Bid Item Materials',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidItemLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(help_text='e.g., Laborer, Operator, Electrician', max_length=100, verbose_name='Classification')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hours')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly rate (including burden)', max_digits=10, verbose_name='Rate')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Cost')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor', to='bid.biditem')),
            ],
            options={
                'verbose_name': 'Bid Item Labor',
                'verbose_name_plural': 'Bid Item Labor',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidItemEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.CharField(help_text='e.g., Excavator, Loader, Truck', max_length=100, verbose_name='Equipment Type')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hours')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly rental rate', max_digits=10, verbose_name='Rate')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Cost')),
                ('fuel_gallons', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Fuel (Gallons)')),
                ('fuel_cost_per_gallon', models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=5, verbose_name='Fuel Cost/Gallon')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='bid.biditem')),
            ],
            options={
                'verbose_name': 'Bid Item Equipment',
                'verbose_name_plural': 'Bid Item Equipment',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='biditem',
            name='bid_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='bid.bidschedule'),
        ),
    ]
