name: Build and deploy Laurel Application

on:
  pull_request: # Build will happen on PR creation
    types: [opened, synchronize]
  push:
    branches:
      - main # Deployment (dev and prod) happens after merging to main
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        type: choice
        description: 'Azure Environment for deployment'
        required: true
        default: 'dev'
        options:
          - 'dev'
          - 'prod'

jobs:
  # Build job that runs when a PR is opened
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  # Dev deployment job that triggers only after merging into the main branch or via manual dispatch
  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'dev' # Dev deployment only from main branch or manually for dev environment
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: '63d8c1a5-9944-4003-b6c7-24ce70956a9b'
          tenant-id: '11855f13-2464-464a-8e0a-b51873160cd3'
          subscription-id: 'cffda582-a060-4e87-994f-9cff463aa651'

      - name: 'Deploy to Azure Web App - Development'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laurelag-dev-eastus-webapp'
          slot-name: 'Development'
          startup-command: './startup.sh'

  # Prod deployment job that triggers after dev deployment or via manual dispatch
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev # Prod deployment happens after dev deployment is successful
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'prod' # Prod deployment only from main branch or manually for prod environment
    environment:
      name: 'Production'
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: '63d8c1a5-9944-4003-b6c7-24ce70956a9b'
          tenant-id: '11855f13-2464-464a-8e0a-b51873160cd3'
          subscription-id: 'cffda582-a060-4e87-994f-9cff463aa651'

      - name: 'Deploy to Azure Web App - Production'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laurelag-prod-eastus-webapp'
          slot-name: 'Production'
          startup-command: './startup.sh'
