name: Deploy To New Prod Environment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Prepare deployment
        run: |
          # Clean up any local environments
          rm -rf venv .venv __pycache__ .pytest_cache
          
          # Create deployment configuration WITHOUT Oryx
          echo "[config]" > .deployment
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=false" >> .deployment
          
          # Make startup script executable
          chmod +x startup.sh
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'laurelag-prod-eastus-webapp'
          package: .
          startup-command: './startup.sh'
